<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pushstream" nsURI="https://geckoprojects.org/model/emf/pushstream/1.0"
    nsPrefix="pushstream">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="suppressInterfaces" value="false"/>
    <details key="containmentProxies" value="true"/>
    <details key="basePackage" value="geckoprojects.org"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EDataType" name="EPushStream" instanceTypeName="org.osgi.util.pushstream.PushStream&lt;org.eclipse.emf.ecore.EObject>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PushStreamProvider" instanceClassName="org.osgi.util.pushstream.PushStreamProvider"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PushStreamBuilder" instanceTypeName="org.osgi.util.pushstream.PushStreamBuilder&lt;org.eclipse.emf.ecore.EObject, java.util.concurrent.BlockingQueue&lt;org.osgi.util.pushstream.PushEvent&lt;? extends org.eclipse.emf.ecore.EObject>>>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ESimplePushEventSource" instanceTypeName="org.osgi.util.pushstream.SimplePushEventSource&lt;org.eclipse.emf.ecore.EObject>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EPushEventSource" instanceTypeName="org.osgi.util.pushstream.PushEventSource&lt;org.eclipse.emf.ecore.EObject>"/>
  <eClassifiers xsi:type="ecore:EClass" name="EPushStreamProvider" abstract="true"
      interface="true">
    <eOperations name="createPushStream" lowerBound="1" eType="#//EPushStream">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="PushStreamProvider psp = getProvider();&#xA;if (psp == null) {&#xA;&#x9;throw new &lt;%java.lang.IllegalArgumentException%>(&quot;PushStreamProvider must not be null to build a PushStream&quot;);&#xA;}&#xA;&lt;%org.osgi.util.pushstream.PushEventSource%>&lt;EObject> es = getEventSource();&#xA;if (es == null) {&#xA;&#x9;throw new &lt;%java.lang.IllegalArgumentException%>(&quot;SimpleEventSource must not be null to build a PushStream&quot;);&#xA;}&#xA;return psp.buildStream(es).build();&#xA;"/>
        <details key="documentation" value="Creates a PushStream from the internal eventSource feature"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="createSimplePushEventSource" lowerBound="1" eType="#//ESimplePushEventSource">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="PushStreamProvider psp = getProvider();&#xA;if (psp == null) {&#xA;&#x9;throw new &lt;%java.lang.IllegalArgumentException%>(&quot;PushStreamProvider must not be null to create a SimplePushEventSource&quot;);&#xA;}&#xA;return psp.buildSimpleEventSource(EObject.class).build();&#xA;"/>
        <details key="documentation" value="Creates a new SimplePushEventSource from the given PushStreamProvider"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="createPushStreamUnbuffered" lowerBound="1" eType="#//EPushStream">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="PushStreamProvider psp = getProvider();&#xA;if (psp == null) {&#xA;&#x9;throw new &lt;%java.lang.IllegalArgumentException%>(&quot;PushStreamProvider must not be null to build a PushStream&quot;);&#xA;}&#xA;&lt;%org.osgi.util.pushstream.PushEventSource%>&lt;EObject> es = getEventSource();&#xA;if (es == null) {&#xA;&#x9;throw new &lt;%java.lang.IllegalArgumentException%>(&quot;SimpleEventSource must not be null to build a PushStream&quot;);&#xA;}&#xA;return psp.buildStream(es).unbuffered().build();&#xA;"/>
        <details key="documentation" value="Creates a PushStream from the internal eventSource feature"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="createPushStreamBuilder" eType="#//PushStreamBuilder">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="PushStreamProvider psp = getProvider();&#xD;&#xA;if (psp == null) {&#xD;&#xA;&#x9;throw new &lt;%java.lang.IllegalArgumentException%>(&quot;PushStreamProvider must not be null to build a PushStream&quot;);&#xD;&#xA;}&#xD;&#xA;&lt;%org.osgi.util.pushstream.PushEventSource%>&lt;EObject> es = getEventSource();&#xD;&#xA;if (es == null) {&#xD;&#xA;&#x9;throw new &lt;%java.lang.IllegalArgumentException%>(&quot;SimpleEventSource must not be null to build a PushStream&quot;);&#xD;&#xA;}&#xD;&#xA;return psp.buildStream(es);&#xD;&#xA;"/>
        <details key="documentation" value="Creates a PushStreamBuilder to customize the settings"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimplePushStreamProvider" eSuperTypes="#//EPushStreamProvider">
    <eOperations name="publishEObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="SimplePushEventSource&lt;EObject> es = getEventSource();&#xA;if (eObject != null &amp;&amp; es != null) {&#xA;&#x9;es.publish(eObject);&#xA;};"/>
        <details key="documentation" value="Publishes an EObject into the internal eventSource"/>
      </eAnnotations>
      <eParameters name="eObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="provider" lowerBound="1"
        eType="#//PushStreamProvider"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="internalSource" eType="#//ESimplePushEventSource"
        changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedGetVisibility" value="true"/>
        <details key="documentation" value="We hide the getter for internal source in the interface only. It is used as holder for th e eventSource attribute. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventSource" lowerBound="1"
        eType="#//ESimplePushEventSource" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="get" value="if (internalSource == null) {&#xD;&#xA;&#x9;internalSource = createSimplePushEventSource();&#xD;&#xA;}&#xD;&#xA;return internalSource;"/>
        <details key="documentation" value="We generate the code for the getter and lazy intialize the internalSource feature"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomPushStreamProvider" eSuperTypes="#//EPushStreamProvider">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventSource" lowerBound="1"
        eType="#//EPushEventSource" transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="provider" lowerBound="1"
        eType="#//PushStreamProvider"/>
  </eClassifiers>
</ecore:EPackage>
